import './globals.css'
import { StateContext } from '@/context/StateContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StateContext>
        <body>{children}</body>
      </StateContext>
    </html>
  )
}
